language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
    only:
        - master
# command to install dependencies
install:
  - pip install Django
# command to run tests
script:
    - DJANGO_SETTINGS_MODULE="xuzhao.markdown.travis_test.travis_settings" test xuzhao.markdown
after_success:
    - coveralls