language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
env:
  global:
    - DJANGO_SETTINGS_MODULE="xuzhao.markdown.travis_test.travis_settings"
branches:
    only:
        - master
# command to install dependencies
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install Django
  - pip install python-coveralls
  - pip install coverage
# command to run tests
script:
    - coverage run manage.py test
after_success:
    - coveralls