language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
    only:
        - master
# command to install dependencies
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install -e .
  - pip install -q Django==$DJANGO
# command to run tests
script:
    - DJANGO_SETTINGS_MODULE=xuzhao.markdown.travis_test.travis_settings django-admin test xuzhao.markdown
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: pypy
      env: DJANGO=2.0