language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install -e .
  - pip install -q Django==$DJANGO
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: pypy
      env: DJANGO=2.0