language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
    only:
        - master
# command to install dependencies
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install -q Django==$DJANGO
  - pip install python-coveralls
  - pip install coverage
# command to run tests
script:
    - coverage run manage.py test
after_success:
    - coveralls
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: pypy
      env: DJANGO=2.0